.PHONY: clean All

All:
	@echo "----------Building project:[ progetto - Debug ]----------"
	@cd "progetto" && "$(MAKE)" -f  "progetto.mk"
clean:
	@echo "----------Cleaning project:[ progetto - Debug ]----------"
	@cd "progetto" && "$(MAKE)" -f  "progetto.mk" clean
